namespace EldanToolkit.Shared
{
	public enum GameTableName
	{
		CharacterCustomization,
		CharacterCustomizationLabel,
		CharacterCustomizationSelection,
		ColorShift,
		Creature2,
		Creature2DisplayGroupEntry,
		Creature2DisplayInfo,
		Creature2OutfitGroupEntry,
		Creature2OutfitInfo,
		DyeColorRamp,
		Emotes,
		HookAsset,
		HousingDecorInfo,
		HousingDecorType,
		HousingPlugItem,
		HousingWallpaperInfo,
		Item2,
		ItemColorSet,
		ItemDisplay,
		ItemSpecial,
		Spell4,
		Spell4Base,
		Spell4Effects,
		UnitVehicle,
		WorldLayer
	}
}
